//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUEncoder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AviUtl_Path {
            get {
                return ((string)(this["AviUtl_Path"]));
            }
            set {
                this["AviUtl_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Profile_Number {
            get {
                return ((string)(this["Profile_Number"]));
            }
            set {
                this["Profile_Number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Plugin_Number {
            get {
                return ((string)(this["Plugin_Number"]));
            }
            set {
                this["Plugin_Number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Find_Ext {
            get {
                return ((string)(this["Find_Ext"]));
            }
            set {
                this["Find_Ext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Output_Ext {
            get {
                return ((string)(this["Output_Ext"]));
            }
            set {
                this["Output_Ext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<ProfileLabel> Profile_Labels {
            get {
                return ((global::System.Collections.Generic.List<ProfileLabel>)(this["Profile_Labels"]));
            }
            set {
                this["Profile_Labels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<PluginLabel> Plugin_Labels {
            get {
                return ((global::System.Collections.Generic.List<PluginLabel>)(this["Plugin_Labels"]));
            }
            set {
                this["Plugin_Labels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Use_Indexer {
            get {
                return ((bool)(this["Use_Indexer"]));
            }
            set {
                this["Use_Indexer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Behavior_After_Encoding {
            get {
                return ((int)(this["Behavior_After_Encoding"]));
            }
            set {
                this["Behavior_After_Encoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Behavior_Quit_Software {
            get {
                return ((bool)(this["Behavior_Quit_Software"]));
            }
            set {
                this["Behavior_Quit_Software"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Behavior_Quit_AviUtl {
            get {
                return ((bool)(this["Behavior_Quit_AviUtl"]));
            }
            set {
                this["Behavior_Quit_AviUtl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Getting_Progress_Interval {
            get {
                return ((int)(this["Getting_Progress_Interval"]));
            }
            set {
                this["Getting_Progress_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_Log {
            get {
                return ((bool)(this["Show_Log"]));
            }
            set {
                this["Show_Log"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Input_Folder_Path {
            get {
                return ((string)(this["Input_Folder_Path"]));
            }
            set {
                this["Input_Folder_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Output_Folder_Path {
            get {
                return ((string)(this["Output_Folder_Path"]));
            }
            set {
                this["Output_Folder_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Follow_Behavior_Setting {
            get {
                return ((bool)(this["Follow_Behavior_Setting"]));
            }
            set {
                this["Follow_Behavior_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Mode {
            get {
                return ((int)(this["Mode"]));
            }
            set {
                this["Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Restore_After_Process {
            get {
                return ((bool)(this["Restore_After_Process"]));
            }
            set {
                this["Restore_After_Process"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Do_File_Analize {
            get {
                return ((bool)(this["Do_File_Analize"]));
            }
            set {
                this["Do_File_Analize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Input_Folder_Last_Selected {
            get {
                return ((string)(this["Input_Folder_Last_Selected"]));
            }
            set {
                this["Input_Folder_Last_Selected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Output_Folder_Last_Selected {
            get {
                return ((string)(this["Output_Folder_Last_Selected"]));
            }
            set {
                this["Output_Folder_Last_Selected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Input_File_Last_Opened {
            get {
                return ((string)(this["Input_File_Last_Opened"]));
            }
            set {
                this["Input_File_Last_Opened"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Video_Codec {
            get {
                return ((int)(this["Video_Codec"]));
            }
            set {
                this["Video_Codec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Audio_Codec {
            get {
                return ((int)(this["Audio_Codec"]));
            }
            set {
                this["Audio_Codec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Video_Bitrate {
            get {
                return ((string)(this["Video_Bitrate"]));
            }
            set {
                this["Video_Bitrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Audio_Bitrate {
            get {
                return ((int)(this["Audio_Bitrate"]));
            }
            set {
                this["Audio_Bitrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Force_Overwrite {
            get {
                return ((bool)(this["Force_Overwrite"]));
            }
            set {
                this["Force_Overwrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-encoded")]
        public string Suffix {
            get {
                return ((string)(this["Suffix"]));
            }
            set {
                this["Suffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Pregenerate_Index_File {
            get {
                return ((bool)(this["Pregenerate_Index_File"]));
            }
            set {
                this["Pregenerate_Index_File"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Frame_Rate {
            get {
                return ((string)(this["Frame_Rate"]));
            }
            set {
                this["Frame_Rate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FFmpeg_Arguments {
            get {
                return ((string)(this["FFmpeg_Arguments"]));
            }
            set {
                this["FFmpeg_Arguments"] = value;
            }
        }
    }
}
